name: Lebedev Home
views:
  - tab_icon: mdi:home
    title: Lights
    theme: dark-mode
    cards:
      - type: entities
        title: Двор
        show_header_toggle: false
        entities:
          - switch.broadlink_yard
      - type: entities
        title: Зал
        show_header_toggle: false
        entities:
          - switch.broadlink_hall_enterance
          - light.yeelight_rgb_34ce008b8b60
      - type: entities
        title: Кухня
        show_header_toggle: false
        entities:
          - sensor.illumination_158d0001e5e3a2
          - switch.broadlink_kitchen
      - type: entities
        title: Коридор
        show_header_toggle: false
        entities:
          # - sensor.illumination_34ce0088d30f
          - light.yeelight_white_34ce008867ea
      - type: entities
        title: Спальня
        show_header_toggle: false
        entities:
          - light.yeelight_rgb_34ce00912999
      - type: entities
        title: 2 этаж
        show_header_toggle: false
        entities:
          - switch.broadlink_2floor
          - light.yeelight_rgb_34ce0084a799
  - tab_icon: mdi:security
    title: Охрана
    cards:
      - type: entity-filter
        title: Кто дома
        entities:
          - device_tracker.samsunggalaxys7
          - device_tracker.androide080cfbd841dcb82
          - device_tracker.c49a02676acf
          - device_tracker.android97367da2dcf80ca2
          - device_tracker.android5b0bb71f36701beb
        state_filter:
          - home
      - type: picture-glance
        title: Двор
        entities:
          - switch.broadlink_yard
        camera_image: camera.Yard_camera 
      - type: picture-glance
        title: Кухня и зал
        entities:
          - binary_sensor.motion_sensor_158d0001e5e3a2
          - binary_sensor.motion_sensor_158d000128b319
        camera_image: camera.floor1_hall_camera
      - type: entities
        title: Коридор
        entities:
          - binary_sensor.door_window_sensor_158d0001b145c6
          - binary_sensor.motion_sensor_158d0001d91dc9
      - type: entities
        title: 2 этаж
        entities:
          - binary_sensor.motion_sensor_158d0001d91d58
  - title: Окружающая среда
    tab_icon: mdi:temperature-celsius
    cards:
      - type: entities
        title: Погода
        entities:
          - sensor.weather_temperature
          - sensor.weather_humidity
      - type: entities
        title: Кухня и зал
        entities:
          - sensor.temperature_158d00019cf466
          - sensor.humidity_158d00019cf466
      - type: entities
        title: Коридор
        entities:
          - sensor.temperature_158d0001216f3b
          - sensor.humidity_158d0001216f3b
      - type: sensor
        entity: sensor.temperature_158d0001216f3b
        name: TTTTTTTTTTTTTTTT
      - type: entities
        title: 2 этаж
        entities:
          - sensor.temperature_158d0001df58de
          - sensor.humidity_158d0001df58de
  - type: entity-filter
    title: Развлечения
    tab_icon: mdi:kodi
    entities:
      - media_player.kodi_pc
      - media_player.kodi_zina
    state_filter:
      - 'playing'
    cards:
      - type: media-control
        entity: media_player.kodi_pc
      - type: media-control
        entity: media_player.kodi_zina
  - tab_icon: mdi:monitoring
    title: Monitoring
    cards:
      - type: entities
        title: nas
        entities:
          - sensor.has_hdd_devsdb
          - sensor.has_hdd_devsdc
          - sensor.has_hdd_devsdd
          - sensor.has_hdd_devsde