  - platform: ping
    host: home.alebedev.photo
    name: internet
  - platform: ping
    host: 10.0.1.70
    name: home10
  - platform: ping
    host: 10.0.1.2
    name: hap_ac2
  - platform: ping
    host: 10.0.1.3
    name: wap_ac
  - platform: ping
    host: 10.0.1.7
    name: NAS
  - platform: ping
    host: 10.0.1.109
    name: xiaomi-gateway
