  - platform: mikrotik
    host: 10.0.1.1
    method: capsman
    username: !secret mikrotik_user
    password: !secret mikrotik_password
    interval_seconds: '10'
    consider_home: '180'
    track_new_devices: 'true'