  - name: 'Наташа'
    id: nata
    device_trackers:
      - device_tracker.80_ce_b9_ce_d9_b9
  - name: 'Андрей'
    id: andrey
    device_trackers:
      - device_tracker.samsunggalaxys7
      - device_tracker.f894c2a110fd
  - name: 'Полина'
    id: polina
    device_trackers:
      - device_tracker.c49a02676acf
      - device_tracker.polina_lg
  - name: 'Баба'
    id: zina
    device_trackers:
      - device_tracker.android97367da2dcf80ca2
      - device_tracker.zina_htc
  - name: 'Дед'
    id: yura
    device_trackers:
      - device_tracker.android5b0bb71f36701beb
      - device_tracker.yura_xiaomi