  yard:
    duration: '00:10:00'
  yard_coming_home:
    duration: '00:03:00'
  koridor:
    duration: '00:03:00'
  2floor:
    duration: '00:03:00'
  kitchen:
    duration: '00:10:00'
  hall:
    duration: '00:03:00'
  hall_night:
    duration: '00:03:00'
  door_alert:
    duration: '00:03:00'
  1h:
    duration: '01:00:00'
  room_polina:
    duration: '00:10:00'