    devices:
      10.0.1.178:
        name: 'lamp'
        save_on_change: 'true'
        model: 'mono1'
      10.0.1.183:
        name: 'RGB-lamp'
        save_on_change: 'true'
        model: 'color1'
      10.0.1.201:
        name: 'RGB-polina-room'
        save_on_change: 'true'
        model: 'color1'
      10.0.1.203:
        name: 'RGB-lamp-2'
        save_on_change: 'true'
        model: 'color1'