# use this file to overcome issues with connection to xiaomi hub
- id: Bad_config
  alias: Bad_config
  hide_entity: True
  trigger:
    - platform: state
      entity_id: binary_sensor.xiaomi_gateway
      from: 'off'
      to: 'on'
  action:
    - service: homeassistant.restart